services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Next.js
      - "3001:3001" # json-server
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - react_node_modules:/app/node_modules
    command: sh -c "npm run json & npm run dev"

  backend:
    build: ./backend/java/backend-api
    ports:
      - "8080:8080"
    volumes:
      - ./backend/java/backend-api:/app
      - /app/target
    environment:
      - SPRING_PROFILES_ACTIVE=dev

volumes:
  react_node_modules:
  target:
