services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Next.js
      - "3001:3001" # json-server
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - react_node_modules:/app/node_modules
    command: sh -c "npm run json & npm run dev"
  backend:
    build: ./backend/java/backend-api
    ports:
      - "8080:8080"
    volumes:
      - ./backend/java/backend-api:/app
      - /app/target
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  fast-api:
    build: ./backend/python/
    volumes:
      - ./backend/python/.dockervenv:/src/.venv
      - ./backend/python:/src
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # rootアカウントをパスワードなしで作成
      MYSQL_DATABASE: 'blog'  # 初期データベースとしてblogを設定
      TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    ports:
      - 33306:3306  # ホストマシンのポート33306を、docker内のポート3306に接続する
volumes:
  react_node_modules:
  target:
  mysql_data:

